# Generated by Django 5.1.1 on 2024-09-16 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(default='QIIL-002080', max_length=10, unique=True)),
                ('event_title', models.CharField(max_length=50)),
                ('event_description', models.TextField()),
                ('event_location', models.CharField(max_length=50)),
                ('event_max_participants', models.PositiveIntegerField()),
                ('event_image', models.ImageField(upload_to='events_images/')),
                ('event_ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event_registration_start', models.DateTimeField()),
                ('event_registration_end', models.DateTimeField()),
                ('event_start_date', models.DateTimeField()),
                ('category', models.ManyToManyField(to='event_app.category')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organizer')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transition_id', models.CharField(default='TJJL-277923', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], max_length=20)),
                ('number_of_participants', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.participant')),
            ],
        ),
    ]
