# Generated by Django 5.1.1 on 2024-09-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(default='EJSD-255299', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='transition_id',
            field=models.CharField(default='VQHS-518385', max_length=10),
        ),
    ]
