# Generated by Django 5.1.1 on 2024-09-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0006_alter_event_event_id_alter_event_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(default='DNDQ-532724', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_ticket_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='transition_id',
            field=models.CharField(default='ASDP-742138', max_length=10),
        ),
    ]
