# Generated by Django 5.1.1 on 2024-09-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0012_participation_event_created_at_alter_event_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(default='HQDI-361821', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='event_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='transition_id',
            field=models.CharField(default='IZEI-065381', max_length=11),
        ),
    ]
