# Generated by Django 5.1.1 on 2024-09-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0013_alter_event_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='is_payment_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(default='UEOW-098396', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='transition_id',
            field=models.CharField(default='DKAO-754892', max_length=11),
        ),
    ]
