# Generated by Django 5.1.1 on 2024-09-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0015_alter_event_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(default='NYTY-759266', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='transition_id',
            field=models.CharField(default='LWGU-392944', max_length=11),
        ),
    ]
