# Generated by Django 5.1.1 on 2024-09-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0016_alter_event_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(default='TQJM-247236', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='transition_id',
            field=models.CharField(default='OZQO-463226', max_length=11),
        ),
    ]
