# Generated by Django 5.1.1 on 2024-09-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0027_remove_participation_user_alter_event_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(default='FTTM-741532', max_length=11, unique=True),
        ),
    ]
