# Generated by Django 5.1.1 on 2024-09-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0028_alter_event_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(default='MSSG-775384', max_length=11, unique=True),
        ),
    ]
